### ISSUE TITLE
Find config vars, add new config vars, and implement into nms code

### ISSUE THREAD

**Issue by Nickforall** [Prismarine/Prismarine#2]
Find all settings in AdvancedSettings.json in nms code.
- [x] Server Closed message -> [PlayerList#765](https://github.com/Prismarine/Prismarine/blob/765183e36ac12be43f823957da01a8fc5bb61e12/src/net/minecraft/server/PlayerList.java#L765)
- [x] Spawnlimits animal
- [x] Spawnlimits hostile
- [x] Spawnlimits ambient
- [x] Spawnlimits water -> [EnumCreatureType#7](https://github.com/Prismarine/Prismarine/blob/master/src/net/minecraft/server/EnumCreatureType.java#L7)
- [ ] Ticks animal spawn
- [ ] Ticks hostile spawn
- [ ] Ticks Autosave
- [x] Ticks Item Despawn => [EntityItem#98](https://github.com/Prismarine/mc-dev/blob/54931c56ab0617341e94ba4487d187e01a215508/net/minecraft/server/EntityItem.java#L98)
